### ISSUE TITLE
[Bug] Does not accept abitrary passwords

### ISSUE THREAD

**Issue by GRBurst** [gustavnikolaj/keepass-dmenu#10] opened 2015-09-16 11:37 UTC
If using a password consisting only of numbers (used by a testdb), one cannot invoke it using the `--password` argument

**Comment by gustavnikolaj** [comment] 2015-09-16 18:45
I think this might be caused by how the yargs-module interpret the command line options. If you quote the password I'm pretty sure it will work.

**Comment by gustavnikolaj** [comment] 2015-09-16 18:55
Released as 1.2.2 on npm.

**Closed** 2015-09-16 18:54 UTC

**Comment by GRBurst** [comment] 2015-09-16 19:04
In fact I even tried to quote it but it did not work ;-)
Now it is working, thanks!

**Comment by gustavnikolaj** [comment] 2015-09-16 19:06
Good :-)
